### PR TITLE
Add self service portal

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Add self service portal
* Update tests to current standard for `go` 1.17
* Update workflows

## why
* Allow users to customize the portal when connecting to the client vpn
* Routine maintenance

## references
* Closes https://github.com/cloudposse/terraform-aws-ec2-client-vpn/issues/34
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_endpoint

```hcl
module "client_vpn" {
  source = "git::https://github.com/cloudposse/terraform-aws-ec2-client-vpn.git?ref=portal"

  # ...
}
```

### CODE REVIEW

**Review by r351574nc3 — DISMISSED** [review]
👍

**Review by Nuru — DISMISSED** [review]

**Comment by Nuru** [comment]
/test terratest
previous test failed with a timeout

**Review by Nuru — APPROVED** [review]

**Pull request merged**
