### PR TITLE
Add support for transport_protocol variable in aws_ec2_client_vpn_endpoint

### LINKED ISSUE #44: Support tcp transport protocol
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[Slack Community](https://slack.cloudposse.com)

## Describe the Feature

Support for configuring vpn transport protocol. Currently, its default which is udp. 

## Expected Behavior

New configurable variable introduced for transport protocol

## Use Case

Sometimes `udp` is not supported Or doesn't work well with all internet providers.

## Describe Ideal Solution

A variable added to `variables.tf` file
```
variable "transport_protocol" {
  description = <<-EOT
    One of `udp` or `tcp`
  EOT
  type = string
  default = "udp"
  validation {
    condition     = contains(["udp", "tcp"], var.transport_protocol)
    error_message = "Invalid protocol type must be one of: udp, tcp."
  }
}
```
Add `transport_protocol    = var.transport_protocol` to https://github.com/cloudposse/terraform-aws-ec2-client-vpn/blob/master/main.tf#L152

Ref: [aws_ec2_client_vpn_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_endpoint#transport_protocol)

### PR DESCRIPTION
**Pull request by s1rc**
## what
The `aws_ec2_client_vpn_endpoint` supports variables for defining the `transport_protocol` as `tcp` or `udp`. Without adding this variable to this module, it will always default to `udp`.

## why
To be able to add `tcp` as a `transport_protocol` for Client VPN Endpoints in Terraform as you would be able to configure in the AWS console.

## references
* closes  #44
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_endpoint#transport_protocol

### CODE REVIEW

**Comment by joe-niland** [comment]
@s1rc thank you for the PR.

Could you please run the following locally and commit the result?

```
make init
make github/init
make readme
```

It will update the GitHub workflows to the latest versions and update the README.

**Comment by s1rc** [comment]
@joe-niland I ran those commands, on `make readme` it is failing with output:

**Comment by joe-niland** [comment]
Hi @s1rc 
OK, no worries, please commit the other files and we'll try to do the readme using Github Actions.

**Comment by s1rc** [comment]
@joe-niland ok, I've pushed the changes from the first two commands.

**Review by joe-niland — APPROVED** [review]

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
