### PR TITLE
Mark 'full_client_configuration' output as sensitive value

### PR DESCRIPTION
**Pull request by VladStarr**
## what
* Add `sensitive=true` option to `full_client_configuration` in `outputs.tf`.

## why
* While using `export_client_certificate = true` we're unable to retrieve the `full_client_configuration` output, because in newer versions of Terraform there is a strict requirement for sensitive outputs to be configured as `sensitive=true`.

### CODE REVIEW

**Comment by ZeroDeth** [comment]
Any plan for merging 
```json
      "client_configuration": {
        "sensitive": true,
        "value": ""
      },
```

**Comment by Gowiem** [comment]
@ZeroDeth Not sure about on your client config JSON question, but we will likely merge this since it’s a simple, easy change. 

Regarding the values being available in PStore — Feel free to open a PR to add that and ping me and we can work through it.

**Review by Gowiem — APPROVED** [review]
LGTM!

**Pull request merged**
